### ISSUE TITLE
SandWorm Intelligence Summary format

### ISSUE THREAD

**Issue by clr2of8** [center-for-threat-informed-defense/adversary_emulation_library#124]
This intelligence summary is different from all the others (looks like the content from the main SandWorm readme vs an Intelligence summary maybe)

https://github.com/center-for-threat-informed-defense/adversary_emulation_library/blob/master/sandworm/Intelligence_Summary/Intelligence_Summary.md

**Comment by cat-alyst** [comment]
You are correct, this is very different from the previous intelligence summaries. 🙌 Thank you for the call out and making an issue, it really helps when we know what the industry is using. 🙏 

When we reviewed previous rounds, the CTI team determined the main difference was the navigator layers & specific software called out. This is repeat work, better represented in [MITRE ATT&CK®](https://attack.mitre.org/). Since this information didn't really add any value we 🪓 it. Future rounds we are hoping to publish a format that better suits Adversary Emulation. Since we have plans to enhance this document, we left it to maintain the consistency of the projects structure.  

A little **background**, this specific contribution was from the ATT&CK Evaluations project. The open-source intelligence research was primarily done by 1 person for every round until October last year (2021), a massive undertaking. We've now grown big enough to have a team 🥳 and are using the bandwidth to be intentional about what is release that will be helpful verses filler content.
